spring:
  application:
    name:
  datasource:
    url: jdbc:mysql://localhost:3306/DocBucket_applied?createDatabaseIfNotExist=true
    username: root
    password: acpt
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8081

